export * from "./metadata";
export * as Avar from "./tables/avar";
export * as Fvar from "./tables/fvar";
export * as Gasp from "./tables/gasp";
export * as Head from "./tables/head";
export * as Maxp from "./tables/maxp";
export * as MetricHead from "./tables/metric-head";
export * as Os2 from "./tables/os2";
export * as Post from "./tables/post";
export * as Vdmx from "./tables/vdmx";
